// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Kind is mostly identical to reflect.TypeKind, expect we handle certain
// types specially, such as "error".
type Type_Kind int32

const (
	Type_INVALID Type_Kind = 0
	// Primitive.
	Type_BOOL    Type_Kind = 1
	Type_INT     Type_Kind = 2
	Type_INT8    Type_Kind = 3
	Type_INT16   Type_Kind = 4
	Type_INT32   Type_Kind = 5
	Type_INT64   Type_Kind = 6
	Type_UINT    Type_Kind = 7
	Type_UINT8   Type_Kind = 8
	Type_UINT16  Type_Kind = 9
	Type_UINT32  Type_Kind = 10
	Type_UINT64  Type_Kind = 11
	Type_STRING  Type_Kind = 12
	Type_FLOAT32 Type_Kind = 13
	Type_FLOAT64 Type_Kind = 14
	// Non-primitive types.
	Type_SLICE    Type_Kind = 20
	Type_STRUCT   Type_Kind = 21
	Type_FUNC     Type_Kind = 22
	Type_CHAN     Type_Kind = 23
	Type_PTR      Type_Kind = 24
	Type_SPECIAL  Type_Kind = 25
	Type_EXTERNAL Type_Kind = 26
)

var Type_Kind_name = map[int32]string{
	0:  "INVALID",
	1:  "BOOL",
	2:  "INT",
	3:  "INT8",
	4:  "INT16",
	5:  "INT32",
	6:  "INT64",
	7:  "UINT",
	8:  "UINT8",
	9:  "UINT16",
	10: "UINT32",
	11: "UINT64",
	12: "STRING",
	13: "FLOAT32",
	14: "FLOAT64",
	20: "SLICE",
	21: "STRUCT",
	22: "FUNC",
	23: "CHAN",
	24: "PTR",
	25: "SPECIAL",
	26: "EXTERNAL",
}

var Type_Kind_value = map[string]int32{
	"INVALID":  0,
	"BOOL":     1,
	"INT":      2,
	"INT8":     3,
	"INT16":    4,
	"INT32":    5,
	"INT64":    6,
	"UINT":     7,
	"UINT8":    8,
	"UINT16":   9,
	"UINT32":   10,
	"UINT64":   11,
	"STRING":   12,
	"FLOAT32":  13,
	"FLOAT64":  14,
	"SLICE":    20,
	"STRUCT":   21,
	"FUNC":     22,
	"CHAN":     23,
	"PTR":      24,
	"SPECIAL":  25,
	"EXTERNAL": 26,
}

func (x Type_Kind) String() string {
	return proto.EnumName(Type_Kind_name, int32(x))
}

func (Type_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{0, 0}
}

// ChanDir matches reflect.ChanDir.
type Type_ChanDir int32

const (
	Type_RECV Type_ChanDir = 0
	Type_SEND Type_ChanDir = 1
	Type_BOTH Type_ChanDir = 2
)

var Type_ChanDir_name = map[int32]string{
	0: "RECV",
	1: "SEND",
	2: "BOTH",
}

var Type_ChanDir_value = map[string]int32{
	"RECV": 0,
	"SEND": 1,
	"BOTH": 2,
}

func (x Type_ChanDir) String() string {
	return proto.EnumName(Type_ChanDir_name, int32(x))
}

func (Type_ChanDir) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{0, 1}
}

type Type_Special int32

const (
	Type_ILLEGAL Type_Special = 0
	// Go
	Type_ERROR   Type_Special = 1
	Type_CONTEXT Type_Special = 2
	Type_TYPE    Type_Special = 3
	// Beam
	Type_EVENTTIME     Type_Special = 10
	Type_WINDOW        Type_Special = 22
	Type_KV            Type_Special = 11
	Type_COGBK         Type_Special = 13
	Type_WINDOWEDVALUE Type_Special = 14
	Type_T             Type_Special = 15
	Type_U             Type_Special = 16
	Type_V             Type_Special = 17
	Type_W             Type_Special = 18
	Type_X             Type_Special = 19
	Type_Y             Type_Special = 20
	Type_Z             Type_Special = 21
)

var Type_Special_name = map[int32]string{
	0:  "ILLEGAL",
	1:  "ERROR",
	2:  "CONTEXT",
	3:  "TYPE",
	10: "EVENTTIME",
	22: "WINDOW",
	11: "KV",
	13: "COGBK",
	14: "WINDOWEDVALUE",
	15: "T",
	16: "U",
	17: "V",
	18: "W",
	19: "X",
	20: "Y",
	21: "Z",
}

var Type_Special_value = map[string]int32{
	"ILLEGAL":       0,
	"ERROR":         1,
	"CONTEXT":       2,
	"TYPE":          3,
	"EVENTTIME":     10,
	"WINDOW":        22,
	"KV":            11,
	"COGBK":         13,
	"WINDOWEDVALUE": 14,
	"T":             15,
	"U":             16,
	"V":             17,
	"W":             18,
	"X":             19,
	"Y":             20,
	"Z":             21,
}

func (x Type_Special) String() string {
	return proto.EnumName(Type_Special_name, int32(x))
}

func (Type_Special) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{0, 2}
}

type MultiEdge_Inbound_InputKind int32

const (
	MultiEdge_Inbound_INVALID   MultiEdge_Inbound_InputKind = 0
	MultiEdge_Inbound_MAIN      MultiEdge_Inbound_InputKind = 1
	MultiEdge_Inbound_SINGLETON MultiEdge_Inbound_InputKind = 2
	MultiEdge_Inbound_SLICE     MultiEdge_Inbound_InputKind = 3
	MultiEdge_Inbound_MAP       MultiEdge_Inbound_InputKind = 4
	MultiEdge_Inbound_MULTIMAP  MultiEdge_Inbound_InputKind = 5
	MultiEdge_Inbound_ITER      MultiEdge_Inbound_InputKind = 6
	MultiEdge_Inbound_REITER    MultiEdge_Inbound_InputKind = 7
)

var MultiEdge_Inbound_InputKind_name = map[int32]string{
	0: "INVALID",
	1: "MAIN",
	2: "SINGLETON",
	3: "SLICE",
	4: "MAP",
	5: "MULTIMAP",
	6: "ITER",
	7: "REITER",
}

var MultiEdge_Inbound_InputKind_value = map[string]int32{
	"INVALID":   0,
	"MAIN":      1,
	"SINGLETON": 2,
	"SLICE":     3,
	"MAP":       4,
	"MULTIMAP":  5,
	"ITER":      6,
	"REITER":    7,
}

func (x MultiEdge_Inbound_InputKind) String() string {
	return proto.EnumName(MultiEdge_Inbound_InputKind_name, int32(x))
}

func (MultiEdge_Inbound_InputKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{7, 0, 0}
}

// Type represents a serializable reflect.Type.
type Type struct {
	// (Required) Type kind.
	Kind Type_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=org.apache.beam.core.runtime.graphx.v1.Type_Kind" json:"kind,omitempty"`
	// (Optional) Element type (if SLICE, PTR or CHAN)
	Element *Type `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
	// (Optional) Fields (if STRUCT).
	Fields []*Type_StructField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// (Optional) Parameter types (if FUNC).
	ParameterTypes []*Type `protobuf:"bytes,4,rep,name=parameter_types,json=parameterTypes,proto3" json:"parameter_types,omitempty"`
	// (Optional) Return types (if FUNC).
	ReturnTypes []*Type `protobuf:"bytes,5,rep,name=return_types,json=returnTypes,proto3" json:"return_types,omitempty"`
	// (Optional) Is variadic (if FUNC).
	IsVariadic bool `protobuf:"varint,6,opt,name=is_variadic,json=isVariadic,proto3" json:"is_variadic,omitempty"`
	// (Optional) Channel direction (if CHAN).
	ChanDir Type_ChanDir `protobuf:"varint,7,opt,name=chan_dir,json=chanDir,proto3,enum=org.apache.beam.core.runtime.graphx.v1.Type_ChanDir" json:"chan_dir,omitempty"`
	// (Optional) Special type (if SPECIAL)
	Special Type_Special `protobuf:"varint,8,opt,name=special,proto3,enum=org.apache.beam.core.runtime.graphx.v1.Type_Special" json:"special,omitempty"`
	// (Optional) Key for external types.
	// External types are types that are not directly serialized using
	// the types above, but rather indirectly serialized.  The wire format
	// holds a lookup key into a registry to reify the types in a worker from a
	// registry. The main usage of external serialization is to preserve
	// methods attached to types.
	ExternalKey          string   `protobuf:"bytes,9,opt,name=external_key,json=externalKey,proto3" json:"external_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{0}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetKind() Type_Kind {
	if m != nil {
		return m.Kind
	}
	return Type_INVALID
}

func (m *Type) GetElement() *Type {
	if m != nil {
		return m.Element
	}
	return nil
}

func (m *Type) GetFields() []*Type_StructField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Type) GetParameterTypes() []*Type {
	if m != nil {
		return m.ParameterTypes
	}
	return nil
}

func (m *Type) GetReturnTypes() []*Type {
	if m != nil {
		return m.ReturnTypes
	}
	return nil
}

func (m *Type) GetIsVariadic() bool {
	if m != nil {
		return m.IsVariadic
	}
	return false
}

func (m *Type) GetChanDir() Type_ChanDir {
	if m != nil {
		return m.ChanDir
	}
	return Type_RECV
}

func (m *Type) GetSpecial() Type_Special {
	if m != nil {
		return m.Special
	}
	return Type_ILLEGAL
}

func (m *Type) GetExternalKey() string {
	if m != nil {
		return m.ExternalKey
	}
	return ""
}

// StructField matches reflect.StructField.
type Type_StructField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PkgPath              string   `protobuf:"bytes,2,opt,name=pkg_path,json=pkgPath,proto3" json:"pkg_path,omitempty"`
	Type                 *Type    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Tag                  string   `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Offset               int64    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Index                []int32  `protobuf:"varint,6,rep,packed,name=index,proto3" json:"index,omitempty"`
	Anonymous            bool     `protobuf:"varint,7,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type_StructField) Reset()         { *m = Type_StructField{} }
func (m *Type_StructField) String() string { return proto.CompactTextString(m) }
func (*Type_StructField) ProtoMessage()    {}
func (*Type_StructField) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{0, 0}
}

func (m *Type_StructField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type_StructField.Unmarshal(m, b)
}
func (m *Type_StructField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type_StructField.Marshal(b, m, deterministic)
}
func (m *Type_StructField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type_StructField.Merge(m, src)
}
func (m *Type_StructField) XXX_Size() int {
	return xxx_messageInfo_Type_StructField.Size(m)
}
func (m *Type_StructField) XXX_DiscardUnknown() {
	xxx_messageInfo_Type_StructField.DiscardUnknown(m)
}

var xxx_messageInfo_Type_StructField proto.InternalMessageInfo

func (m *Type_StructField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type_StructField) GetPkgPath() string {
	if m != nil {
		return m.PkgPath
	}
	return ""
}

func (m *Type_StructField) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Type_StructField) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Type_StructField) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Type_StructField) GetIndex() []int32 {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Type_StructField) GetAnonymous() bool {
	if m != nil {
		return m.Anonymous
	}
	return false
}

// FullType represents a serialized typex.FullType
type FullType struct {
	Type                 *Type       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Components           []*FullType `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FullType) Reset()         { *m = FullType{} }
func (m *FullType) String() string { return proto.CompactTextString(m) }
func (*FullType) ProtoMessage()    {}
func (*FullType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{1}
}

func (m *FullType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullType.Unmarshal(m, b)
}
func (m *FullType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullType.Marshal(b, m, deterministic)
}
func (m *FullType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullType.Merge(m, src)
}
func (m *FullType) XXX_Size() int {
	return xxx_messageInfo_FullType.Size(m)
}
func (m *FullType) XXX_DiscardUnknown() {
	xxx_messageInfo_FullType.DiscardUnknown(m)
}

var xxx_messageInfo_FullType proto.InternalMessageInfo

func (m *FullType) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *FullType) GetComponents() []*FullType {
	if m != nil {
		return m.Components
	}
	return nil
}

// UserFn represents a serialized function reference. The
// implementation is notably not serialized and must be present (and
// somehow discoverable from the symbol name) on the decoding side.
type UserFn struct {
	// (Required) Symbol name of function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) Function type.
	Type                 *Type    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFn) Reset()         { *m = UserFn{} }
func (m *UserFn) String() string { return proto.CompactTextString(m) }
func (*UserFn) ProtoMessage()    {}
func (*UserFn) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{2}
}

func (m *UserFn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFn.Unmarshal(m, b)
}
func (m *UserFn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFn.Marshal(b, m, deterministic)
}
func (m *UserFn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFn.Merge(m, src)
}
func (m *UserFn) XXX_Size() int {
	return xxx_messageInfo_UserFn.Size(m)
}
func (m *UserFn) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFn.DiscardUnknown(m)
}

var xxx_messageInfo_UserFn proto.InternalMessageInfo

func (m *UserFn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserFn) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

// DynFn represents a serialized function generator.
type DynFn struct {
	// (Required) Name of the generated function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) Type of the generated function.
	Type *Type `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// (Required) Input to generator.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// (Required) Symbol name of generator (of type []byte ->
	// []reflect.Value -> []reflect.Value).
	Gen                  string   `protobuf:"bytes,4,opt,name=gen,proto3" json:"gen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynFn) Reset()         { *m = DynFn{} }
func (m *DynFn) String() string { return proto.CompactTextString(m) }
func (*DynFn) ProtoMessage()    {}
func (*DynFn) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{3}
}

func (m *DynFn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynFn.Unmarshal(m, b)
}
func (m *DynFn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynFn.Marshal(b, m, deterministic)
}
func (m *DynFn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynFn.Merge(m, src)
}
func (m *DynFn) XXX_Size() int {
	return xxx_messageInfo_DynFn.Size(m)
}
func (m *DynFn) XXX_DiscardUnknown() {
	xxx_messageInfo_DynFn.DiscardUnknown(m)
}

var xxx_messageInfo_DynFn proto.InternalMessageInfo

func (m *DynFn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DynFn) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *DynFn) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DynFn) GetGen() string {
	if m != nil {
		return m.Gen
	}
	return ""
}

// Fn represents a serialized function reference or struct.
type Fn struct {
	// (Optional) Function reference.
	Fn *UserFn `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	// (Optional) Struct type.
	Type *Type `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// (Optional) JSON-serialized value, if struct.
	Opt string `protobuf:"bytes,3,opt,name=opt,proto3" json:"opt,omitempty"`
	// (Optional) Function generator, if dynamic function.
	Dynfn                *DynFn   `protobuf:"bytes,4,opt,name=dynfn,proto3" json:"dynfn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fn) Reset()         { *m = Fn{} }
func (m *Fn) String() string { return proto.CompactTextString(m) }
func (*Fn) ProtoMessage()    {}
func (*Fn) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{4}
}

func (m *Fn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fn.Unmarshal(m, b)
}
func (m *Fn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fn.Marshal(b, m, deterministic)
}
func (m *Fn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fn.Merge(m, src)
}
func (m *Fn) XXX_Size() int {
	return xxx_messageInfo_Fn.Size(m)
}
func (m *Fn) XXX_DiscardUnknown() {
	xxx_messageInfo_Fn.DiscardUnknown(m)
}

var xxx_messageInfo_Fn proto.InternalMessageInfo

func (m *Fn) GetFn() *UserFn {
	if m != nil {
		return m.Fn
	}
	return nil
}

func (m *Fn) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Fn) GetOpt() string {
	if m != nil {
		return m.Opt
	}
	return ""
}

func (m *Fn) GetDynfn() *DynFn {
	if m != nil {
		return m.Dynfn
	}
	return nil
}

// WindowFn represents a window fn.
type WindowFn struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	SizeMs               int64    `protobuf:"varint,2,opt,name=size_ms,json=sizeMs,proto3" json:"size_ms,omitempty"`
	PeriodMs             int64    `protobuf:"varint,3,opt,name=period_ms,json=periodMs,proto3" json:"period_ms,omitempty"`
	GapMs                int64    `protobuf:"varint,4,opt,name=gap_ms,json=gapMs,proto3" json:"gap_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowFn) Reset()         { *m = WindowFn{} }
func (m *WindowFn) String() string { return proto.CompactTextString(m) }
func (*WindowFn) ProtoMessage()    {}
func (*WindowFn) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{5}
}

func (m *WindowFn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowFn.Unmarshal(m, b)
}
func (m *WindowFn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowFn.Marshal(b, m, deterministic)
}
func (m *WindowFn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowFn.Merge(m, src)
}
func (m *WindowFn) XXX_Size() int {
	return xxx_messageInfo_WindowFn.Size(m)
}
func (m *WindowFn) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowFn.DiscardUnknown(m)
}

var xxx_messageInfo_WindowFn proto.InternalMessageInfo

func (m *WindowFn) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *WindowFn) GetSizeMs() int64 {
	if m != nil {
		return m.SizeMs
	}
	return 0
}

func (m *WindowFn) GetPeriodMs() int64 {
	if m != nil {
		return m.PeriodMs
	}
	return 0
}

func (m *WindowFn) GetGapMs() int64 {
	if m != nil {
		return m.GapMs
	}
	return 0
}

// CustomCoder
type CustomCoder struct {
	// (Required) Name of the coder. For informational purposes only.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) Concrete type being coded.
	Type *Type `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// (Required) Encoding function.
	Enc *UserFn `protobuf:"bytes,3,opt,name=enc,proto3" json:"enc,omitempty"`
	// (Required) Decoding function.
	Dec                  *UserFn  `protobuf:"bytes,4,opt,name=dec,proto3" json:"dec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomCoder) Reset()         { *m = CustomCoder{} }
func (m *CustomCoder) String() string { return proto.CompactTextString(m) }
func (*CustomCoder) ProtoMessage()    {}
func (*CustomCoder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{6}
}

func (m *CustomCoder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomCoder.Unmarshal(m, b)
}
func (m *CustomCoder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomCoder.Marshal(b, m, deterministic)
}
func (m *CustomCoder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomCoder.Merge(m, src)
}
func (m *CustomCoder) XXX_Size() int {
	return xxx_messageInfo_CustomCoder.Size(m)
}
func (m *CustomCoder) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomCoder.DiscardUnknown(m)
}

var xxx_messageInfo_CustomCoder proto.InternalMessageInfo

func (m *CustomCoder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomCoder) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *CustomCoder) GetEnc() *UserFn {
	if m != nil {
		return m.Enc
	}
	return nil
}

func (m *CustomCoder) GetDec() *UserFn {
	if m != nil {
		return m.Dec
	}
	return nil
}

// MultiEdge represents a partly-serialized MultiEdge. It does not include
// node information, because runners manipulate the graph structure.
type MultiEdge struct {
	Fn                   *Fn                   `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Opcode               string                `protobuf:"bytes,4,opt,name=opcode,proto3" json:"opcode,omitempty"`
	WindowFn             *WindowFn             `protobuf:"bytes,5,opt,name=window_fn,json=windowFn,proto3" json:"window_fn,omitempty"`
	Inbound              []*MultiEdge_Inbound  `protobuf:"bytes,2,rep,name=inbound,proto3" json:"inbound,omitempty"`
	Outbound             []*MultiEdge_Outbound `protobuf:"bytes,3,rep,name=outbound,proto3" json:"outbound,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MultiEdge) Reset()         { *m = MultiEdge{} }
func (m *MultiEdge) String() string { return proto.CompactTextString(m) }
func (*MultiEdge) ProtoMessage()    {}
func (*MultiEdge) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{7}
}

func (m *MultiEdge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiEdge.Unmarshal(m, b)
}
func (m *MultiEdge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiEdge.Marshal(b, m, deterministic)
}
func (m *MultiEdge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiEdge.Merge(m, src)
}
func (m *MultiEdge) XXX_Size() int {
	return xxx_messageInfo_MultiEdge.Size(m)
}
func (m *MultiEdge) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiEdge.DiscardUnknown(m)
}

var xxx_messageInfo_MultiEdge proto.InternalMessageInfo

func (m *MultiEdge) GetFn() *Fn {
	if m != nil {
		return m.Fn
	}
	return nil
}

func (m *MultiEdge) GetOpcode() string {
	if m != nil {
		return m.Opcode
	}
	return ""
}

func (m *MultiEdge) GetWindowFn() *WindowFn {
	if m != nil {
		return m.WindowFn
	}
	return nil
}

func (m *MultiEdge) GetInbound() []*MultiEdge_Inbound {
	if m != nil {
		return m.Inbound
	}
	return nil
}

func (m *MultiEdge) GetOutbound() []*MultiEdge_Outbound {
	if m != nil {
		return m.Outbound
	}
	return nil
}

type MultiEdge_Inbound struct {
	Kind                 MultiEdge_Inbound_InputKind `protobuf:"varint,1,opt,name=kind,proto3,enum=org.apache.beam.core.runtime.graphx.v1.MultiEdge_Inbound_InputKind" json:"kind,omitempty"`
	Type                 *FullType                   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MultiEdge_Inbound) Reset()         { *m = MultiEdge_Inbound{} }
func (m *MultiEdge_Inbound) String() string { return proto.CompactTextString(m) }
func (*MultiEdge_Inbound) ProtoMessage()    {}
func (*MultiEdge_Inbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{7, 0}
}

func (m *MultiEdge_Inbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiEdge_Inbound.Unmarshal(m, b)
}
func (m *MultiEdge_Inbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiEdge_Inbound.Marshal(b, m, deterministic)
}
func (m *MultiEdge_Inbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiEdge_Inbound.Merge(m, src)
}
func (m *MultiEdge_Inbound) XXX_Size() int {
	return xxx_messageInfo_MultiEdge_Inbound.Size(m)
}
func (m *MultiEdge_Inbound) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiEdge_Inbound.DiscardUnknown(m)
}

var xxx_messageInfo_MultiEdge_Inbound proto.InternalMessageInfo

func (m *MultiEdge_Inbound) GetKind() MultiEdge_Inbound_InputKind {
	if m != nil {
		return m.Kind
	}
	return MultiEdge_Inbound_INVALID
}

func (m *MultiEdge_Inbound) GetType() *FullType {
	if m != nil {
		return m.Type
	}
	return nil
}

type MultiEdge_Outbound struct {
	Type                 *FullType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MultiEdge_Outbound) Reset()         { *m = MultiEdge_Outbound{} }
func (m *MultiEdge_Outbound) String() string { return proto.CompactTextString(m) }
func (*MultiEdge_Outbound) ProtoMessage()    {}
func (*MultiEdge_Outbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{7, 1}
}

func (m *MultiEdge_Outbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiEdge_Outbound.Unmarshal(m, b)
}
func (m *MultiEdge_Outbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiEdge_Outbound.Marshal(b, m, deterministic)
}
func (m *MultiEdge_Outbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiEdge_Outbound.Merge(m, src)
}
func (m *MultiEdge_Outbound) XXX_Size() int {
	return xxx_messageInfo_MultiEdge_Outbound.Size(m)
}
func (m *MultiEdge_Outbound) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiEdge_Outbound.DiscardUnknown(m)
}

var xxx_messageInfo_MultiEdge_Outbound proto.InternalMessageInfo

func (m *MultiEdge_Outbound) GetType() *FullType {
	if m != nil {
		return m.Type
	}
	return nil
}

// InjectPayload is the payload for the built-in Inject function.
type InjectPayload struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InjectPayload) Reset()         { *m = InjectPayload{} }
func (m *InjectPayload) String() string { return proto.CompactTextString(m) }
func (*InjectPayload) ProtoMessage()    {}
func (*InjectPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{8}
}

func (m *InjectPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InjectPayload.Unmarshal(m, b)
}
func (m *InjectPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InjectPayload.Marshal(b, m, deterministic)
}
func (m *InjectPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InjectPayload.Merge(m, src)
}
func (m *InjectPayload) XXX_Size() int {
	return xxx_messageInfo_InjectPayload.Size(m)
}
func (m *InjectPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_InjectPayload.DiscardUnknown(m)
}

var xxx_messageInfo_InjectPayload proto.InternalMessageInfo

func (m *InjectPayload) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

// TransformPayload represents the full payload for transforms, both
// user defined and built-in.
type TransformPayload struct {
	// urn is included here. It is also present in the model pipeline, but
	// not when submitting through Dataflow yet.
	Urn                  string         `protobuf:"bytes,1,opt,name=urn,proto3" json:"urn,omitempty"`
	Edge                 *MultiEdge     `protobuf:"bytes,2,opt,name=edge,proto3" json:"edge,omitempty"`
	Inject               *InjectPayload `protobuf:"bytes,3,opt,name=inject,proto3" json:"inject,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransformPayload) Reset()         { *m = TransformPayload{} }
func (m *TransformPayload) String() string { return proto.CompactTextString(m) }
func (*TransformPayload) ProtoMessage()    {}
func (*TransformPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{9}
}

func (m *TransformPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformPayload.Unmarshal(m, b)
}
func (m *TransformPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformPayload.Marshal(b, m, deterministic)
}
func (m *TransformPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformPayload.Merge(m, src)
}
func (m *TransformPayload) XXX_Size() int {
	return xxx_messageInfo_TransformPayload.Size(m)
}
func (m *TransformPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TransformPayload proto.InternalMessageInfo

func (m *TransformPayload) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *TransformPayload) GetEdge() *MultiEdge {
	if m != nil {
		return m.Edge
	}
	return nil
}

func (m *TransformPayload) GetInject() *InjectPayload {
	if m != nil {
		return m.Inject
	}
	return nil
}

func init() {
	proto.RegisterEnum("org.apache.beam.core.runtime.graphx.v1.Type_Kind", Type_Kind_name, Type_Kind_value)
	proto.RegisterEnum("org.apache.beam.core.runtime.graphx.v1.Type_ChanDir", Type_ChanDir_name, Type_ChanDir_value)
	proto.RegisterEnum("org.apache.beam.core.runtime.graphx.v1.Type_Special", Type_Special_name, Type_Special_value)
	proto.RegisterEnum("org.apache.beam.core.runtime.graphx.v1.MultiEdge_Inbound_InputKind", MultiEdge_Inbound_InputKind_name, MultiEdge_Inbound_InputKind_value)
	proto.RegisterType((*Type)(nil), "org.apache.beam.core.runtime.graphx.v1.Type")
	proto.RegisterType((*Type_StructField)(nil), "org.apache.beam.core.runtime.graphx.v1.Type.StructField")
	proto.RegisterType((*FullType)(nil), "org.apache.beam.core.runtime.graphx.v1.FullType")
	proto.RegisterType((*UserFn)(nil), "org.apache.beam.core.runtime.graphx.v1.UserFn")
	proto.RegisterType((*DynFn)(nil), "org.apache.beam.core.runtime.graphx.v1.DynFn")
	proto.RegisterType((*Fn)(nil), "org.apache.beam.core.runtime.graphx.v1.Fn")
	proto.RegisterType((*WindowFn)(nil), "org.apache.beam.core.runtime.graphx.v1.WindowFn")
	proto.RegisterType((*CustomCoder)(nil), "org.apache.beam.core.runtime.graphx.v1.CustomCoder")
	proto.RegisterType((*MultiEdge)(nil), "org.apache.beam.core.runtime.graphx.v1.MultiEdge")
	proto.RegisterType((*MultiEdge_Inbound)(nil), "org.apache.beam.core.runtime.graphx.v1.MultiEdge.Inbound")
	proto.RegisterType((*MultiEdge_Outbound)(nil), "org.apache.beam.core.runtime.graphx.v1.MultiEdge.Outbound")
	proto.RegisterType((*InjectPayload)(nil), "org.apache.beam.core.runtime.graphx.v1.InjectPayload")
	proto.RegisterType((*TransformPayload)(nil), "org.apache.beam.core.runtime.graphx.v1.TransformPayload")
}

func init() {
	proto.RegisterFile("v1.proto", fileDescriptor_2e4aa7d76fd7ee8a)
}

var fileDescriptor_2e4aa7d76fd7ee8a = []byte{
	// 1236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0xcf, 0x92, 0xdb, 0xc4,
	0x13, 0x8e, 0x6c, 0xcb, 0x96, 0xda, 0xbb, 0xc9, 0x64, 0x7e, 0xf9, 0xe3, 0xec, 0x0f, 0x8a, 0xe0,
	0x03, 0xa4, 0x28, 0x50, 0xb1, 0x9b, 0x90, 0x0a, 0x39, 0x50, 0xd9, 0xc8, 0xda, 0xc4, 0xb5, 0xb6,
	0xec, 0x1a, 0xcb, 0xde, 0x24, 0x07, 0x5c, 0x8a, 0x3c, 0xeb, 0x15, 0x6b, 0x4b, 0x2a, 0x49, 0xde,
	0xc4, 0x5c, 0x79, 0x04, 0xee, 0x3c, 0x00, 0xbc, 0x01, 0x57, 0x5e, 0x03, 0xce, 0x3c, 0x06, 0xf4,
	0x8c, 0x24, 0xb3, 0x5b, 0x70, 0xb0, 0x17, 0x72, 0x9a, 0x9e, 0x3f, 0xfd, 0xf9, 0x9b, 0xaf, 0x7b,
	0xba, 0x65, 0xd0, 0xce, 0x76, 0x8d, 0x28, 0x0e, 0xd3, 0x90, 0x7e, 0x14, 0xc6, 0x53, 0xc3, 0x8d,
	0x5c, 0xef, 0x84, 0x1b, 0xaf, 0xb9, 0x3b, 0x37, 0xbc, 0x30, 0xe6, 0x46, 0xbc, 0x08, 0x52, 0x7f,
	0xce, 0x8d, 0x69, 0xec, 0x46, 0x27, 0x6f, 0x8d, 0xb3, 0xdd, 0xe6, 0x4f, 0x00, 0x15, 0x67, 0x19,
	0x71, 0x6a, 0x41, 0xe5, 0xd4, 0x0f, 0x26, 0x0d, 0xe5, 0xae, 0x72, 0xef, 0xea, 0xde, 0xae, 0xb1,
	0x9e, 0xbf, 0x21, 0x7c, 0x8d, 0x43, 0x74, 0x64, 0xd2, 0x9d, 0x1e, 0x40, 0x8d, 0xcf, 0xf8, 0x9c,
	0x07, 0x69, 0xa3, 0x84, 0x48, 0xf5, 0xbd, 0x4f, 0x37, 0x41, 0x62, 0x85, 0x33, 0xed, 0x43, 0xf5,
	0xd8, 0xe7, 0xb3, 0x49, 0xd2, 0x28, 0xdf, 0x2d, 0x23, 0xcc, 0xa3, 0x8d, 0x08, 0x0d, 0xd2, 0x78,
	0xe1, 0xa5, 0x07, 0x02, 0x80, 0xe5, 0x38, 0x74, 0x08, 0xd7, 0x22, 0x37, 0x76, 0xe7, 0x3c, 0xe5,
	0xf1, 0x38, 0xc5, 0x53, 0x49, 0xa3, 0x22, 0xa1, 0x37, 0x63, 0x78, 0x75, 0x05, 0x22, 0xa6, 0x09,
	0xed, 0xc1, 0x56, 0xcc, 0xd3, 0x45, 0x1c, 0xe4, 0x98, 0xea, 0x25, 0x30, 0xeb, 0x19, 0x42, 0x06,
	0xf8, 0x01, 0xd4, 0xfd, 0x64, 0x7c, 0xe6, 0xc6, 0xbe, 0x3b, 0xf1, 0xbd, 0x46, 0x15, 0x55, 0xd4,
	0x18, 0xf8, 0xc9, 0x28, 0x5f, 0xc1, 0x5f, 0xd4, 0xbc, 0x13, 0x37, 0x18, 0x4f, 0xfc, 0xb8, 0x51,
	0x93, 0xd1, 0x7a, 0xb0, 0x91, 0x38, 0x26, 0x3a, 0xb7, 0xfc, 0x98, 0xd5, 0xbc, 0xcc, 0xa0, 0x36,
	0xd4, 0x92, 0x88, 0x7b, 0xbe, 0x3b, 0x6b, 0x68, 0x97, 0xc0, 0x1b, 0x64, 0xbe, 0xac, 0x00, 0xa1,
	0x1f, 0xc2, 0x16, 0x7f, 0x8b, 0x02, 0x05, 0xee, 0x6c, 0x7c, 0xca, 0x97, 0x0d, 0x1d, 0x41, 0x75,
	0x56, 0x2f, 0xd6, 0x0e, 0xf9, 0x72, 0xe7, 0x57, 0x05, 0xea, 0xe7, 0x82, 0x44, 0x29, 0x54, 0x02,
	0x54, 0x55, 0x66, 0x9f, 0xce, 0xa4, 0x4d, 0xef, 0x80, 0x16, 0x9d, 0x4e, 0xc7, 0x91, 0x9b, 0x9e,
	0xc8, 0x5c, 0xd2, 0x59, 0x0d, 0xe7, 0x7d, 0x9c, 0xd2, 0x27, 0x50, 0x11, 0x6a, 0x63, 0x6e, 0x6c,
	0x9e, 0x62, 0xd2, 0x93, 0x12, 0x28, 0xa7, 0xee, 0x14, 0x33, 0x40, 0xe0, 0x0a, 0x93, 0xde, 0x82,
	0x6a, 0x78, 0x7c, 0x9c, 0xf0, 0x14, 0x43, 0xa8, 0xdc, 0x2b, 0xb3, 0x7c, 0x46, 0x6f, 0x80, 0x8a,
	0x89, 0xcd, 0xdf, 0x62, 0x24, 0xca, 0xf7, 0x54, 0x96, 0x4d, 0xe8, 0x7b, 0xa0, 0xbb, 0x41, 0x18,
	0x2c, 0xe7, 0xe1, 0x22, 0x91, 0x51, 0xd0, 0xd8, 0x5f, 0x0b, 0xcd, 0x3f, 0x14, 0xa8, 0x88, 0x47,
	0x41, 0xeb, 0x50, 0x6b, 0xdb, 0xa3, 0xfd, 0x4e, 0xbb, 0x45, 0xae, 0x50, 0x0d, 0x2a, 0x4f, 0x7b,
	0xbd, 0x0e, 0x51, 0x68, 0x0d, 0xca, 0x6d, 0xdb, 0x21, 0x25, 0xb1, 0x84, 0xc6, 0x23, 0x52, 0xa6,
	0x3a, 0xa8, 0x68, 0xed, 0x3e, 0x24, 0x95, 0xdc, 0xbc, 0xbf, 0x47, 0xd4, 0xdc, 0x7c, 0xf8, 0x80,
	0x54, 0xc5, 0xd1, 0xa1, 0x70, 0xaa, 0x89, 0xc5, 0xa1, 0xf4, 0xd2, 0x28, 0x40, 0x75, 0x98, 0xb9,
	0xe9, 0x85, 0x8d, 0x7e, 0x50, 0xd8, 0xe8, 0x58, 0x17, 0xf6, 0xc0, 0x61, 0x6d, 0xfb, 0x19, 0xd9,
	0x12, 0x7c, 0x0e, 0x3a, 0xbd, 0x7d, 0x71, 0x68, 0x7b, 0x35, 0xc1, 0x53, 0x57, 0x05, 0xe8, 0xa0,
	0xd3, 0x36, 0x2d, 0x72, 0x23, 0x77, 0x18, 0x9a, 0x0e, 0xb9, 0x29, 0x7e, 0xf5, 0x60, 0x68, 0x9b,
	0xe4, 0x96, 0xb0, 0xcc, 0xe7, 0xfb, 0x36, 0xb9, 0x2d, 0xd8, 0xf7, 0x1d, 0x46, 0x1a, 0x02, 0x60,
	0xd0, 0xb7, 0xcc, 0xf6, 0x7e, 0x87, 0xdc, 0xa1, 0x5b, 0xa0, 0x59, 0x2f, 0x1c, 0x8b, 0xd9, 0x38,
	0xdb, 0x69, 0x7e, 0x0c, 0xb5, 0x3c, 0xcf, 0x84, 0x23, 0xb3, 0xcc, 0x51, 0x26, 0xc0, 0xc0, 0xb2,
	0x5b, 0x28, 0x80, 0x94, 0xc2, 0x79, 0x4e, 0x4a, 0xcd, 0x1f, 0x15, 0x04, 0xc9, 0x13, 0x47, 0xa8,
	0xd5, 0xe9, 0x58, 0xcf, 0x10, 0xe1, 0x8a, 0x20, 0x64, 0x31, 0xd6, 0x63, 0x78, 0x1a, 0xd7, 0xcd,
	0x9e, 0xed, 0x20, 0x7c, 0x26, 0x99, 0xf3, 0xb2, 0x6f, 0xa1, 0x64, 0xdb, 0xa0, 0x5b, 0x23, 0xcb,
	0x76, 0x9c, 0x76, 0xd7, 0xca, 0xee, 0x7c, 0xd4, 0xb6, 0x5b, 0xbd, 0x23, 0x24, 0x5b, 0x85, 0xd2,
	0xe1, 0x08, 0xef, 0x8e, 0x20, 0x66, 0xef, 0xd9, 0xd3, 0x43, 0xbc, 0xed, 0x75, 0xd8, 0xce, 0xb6,
	0xad, 0x16, 0x06, 0x64, 0x68, 0xe1, 0x9d, 0x55, 0x50, 0x1c, 0x72, 0x4d, 0x0c, 0x43, 0x42, 0xc4,
	0x30, 0x22, 0xd7, 0xc5, 0x70, 0x44, 0xa8, 0x18, 0x5e, 0x90, 0xff, 0x89, 0xe1, 0x25, 0x4a, 0x82,
	0xc3, 0x2b, 0x72, 0xb3, 0xf9, 0x83, 0x02, 0xda, 0xc1, 0x62, 0x36, 0x93, 0x15, 0xb3, 0x48, 0x42,
	0xe5, 0xd2, 0x49, 0xd8, 0x07, 0xf0, 0xc2, 0x79, 0x14, 0x06, 0x58, 0xf1, 0x12, 0xcc, 0x71, 0x51,
	0x39, 0x3e, 0x5f, 0x17, 0xa7, 0xe0, 0xc1, 0xce, 0x61, 0x34, 0xbf, 0xc6, 0xb8, 0x27, 0x3c, 0x3e,
	0x08, 0xfe, 0xf1, 0x45, 0x15, 0x8c, 0x4b, 0x97, 0x65, 0xdc, 0xfc, 0x4e, 0x01, 0xb5, 0xb5, 0x0c,
	0xde, 0x15, 0xbe, 0x40, 0x9d, 0xb8, 0xa9, 0x2b, 0x1f, 0xf6, 0x16, 0x93, 0xb6, 0x78, 0xaa, 0x53,
	0x1e, 0x14, 0x4f, 0x15, 0xcd, 0xe6, 0x6f, 0x0a, 0x94, 0x90, 0xc2, 0x57, 0x50, 0x3a, 0x0e, 0x72,
	0xf9, 0x8d, 0x75, 0x7f, 0x2c, 0x93, 0x87, 0xa1, 0xe7, 0x7f, 0x40, 0x17, 0xa9, 0x85, 0x51, 0x2a,
	0xd9, 0x22, 0x35, 0x34, 0xa9, 0x09, 0xea, 0x64, 0x19, 0x1c, 0x67, 0x74, 0xeb, 0x7b, 0x9f, 0xad,
	0x0b, 0x2a, 0x45, 0x65, 0x99, 0x6f, 0xf3, 0x14, 0xb4, 0x23, 0xac, 0x1e, 0xe1, 0x9b, 0x4c, 0xe7,
	0x55, 0x5f, 0xd6, 0xf3, 0x26, 0x7b, 0x1b, 0x0b, 0xb6, 0xff, 0x2d, 0x1f, 0xcf, 0x13, 0xc9, 0x1d,
	0x6b, 0x95, 0x98, 0x76, 0x13, 0xfa, 0x7f, 0xd0, 0x23, 0x1e, 0xfb, 0xe1, 0x44, 0x6c, 0x95, 0xe5,
	0x96, 0x96, 0x2d, 0xe0, 0xe6, 0x4d, 0xa8, 0x4e, 0xdd, 0x48, 0xec, 0x54, 0xe4, 0x8e, 0x8a, 0xb3,
	0x6e, 0xd2, 0xfc, 0x1d, 0x4b, 0xb1, 0xb9, 0x48, 0xd2, 0x70, 0x6e, 0x86, 0x13, 0x1e, 0xbf, 0xa3,
	0xc0, 0x3e, 0x81, 0x32, 0x0f, 0xbc, 0xbc, 0x60, 0x6f, 0x1a, 0x2c, 0xe1, 0x2a, 0x10, 0x26, 0xdc,
	0xcb, 0x75, 0xdd, 0x18, 0x01, 0x5d, 0x9b, 0xbf, 0xa8, 0xa0, 0x77, 0x17, 0xb3, 0xd4, 0xb7, 0x26,
	0x53, 0x4e, 0x1f, 0x9f, 0xcb, 0x9e, 0x4f, 0xd6, 0x7e, 0x74, 0x59, 0xe6, 0x88, 0x5e, 0x11, 0x79,
	0x28, 0x57, 0x9e, 0x95, 0xf9, 0x8c, 0x76, 0x41, 0x7f, 0x23, 0x03, 0x37, 0x46, 0x68, 0x55, 0x42,
	0xaf, 0xfd, 0x9e, 0x8b, 0x88, 0x33, 0xed, 0x4d, 0x11, 0xfb, 0x01, 0xd4, 0xfc, 0xe0, 0x75, 0xb8,
	0xc0, 0xf0, 0x67, 0xc5, 0xe1, 0xcb, 0x75, 0xc1, 0x56, 0xd7, 0x34, 0xda, 0x19, 0x00, 0x2b, 0x90,
	0xe8, 0x08, 0xb4, 0x70, 0x91, 0x66, 0xa8, 0xd9, 0xb7, 0xd5, 0xe3, 0xcd, 0x51, 0x7b, 0x39, 0x02,
	0x5b, 0x61, 0xed, 0x7c, 0x5f, 0xc2, 0xea, 0x9d, 0xff, 0xc6, 0xd1, 0x85, 0x8f, 0x49, 0xf3, 0xd2,
	0xac, 0x71, 0x8c, 0x16, 0xe9, 0xb9, 0xcf, 0xcb, 0xd6, 0x85, 0x44, 0xdc, 0xbc, 0x56, 0x66, 0x55,
	0xcc, 0x07, 0x7d, 0x05, 0xfc, 0xb7, 0x16, 0xdd, 0xdd, 0x6f, 0xdb, 0xd8, 0x73, 0xb0, 0xb9, 0x0c,
	0xb0, 0x67, 0x76, 0x2c, 0xa7, 0x67, 0x63, 0xd7, 0x59, 0xb5, 0xc7, 0xb2, 0x68, 0x7f, 0xdd, 0xfd,
	0x3e, 0xf6, 0x69, 0xec, 0x78, 0xdd, 0x61, 0x07, 0xbb, 0x0f, 0xce, 0x54, 0xd9, 0xca, 0xb1, 0xfd,
	0x61, 0xa7, 0xc6, 0x46, 0xc4, 0x2c, 0x69, 0xd7, 0x76, 0xfa, 0xa0, 0x15, 0x5a, 0xad, 0xc8, 0x2b,
	0xff, 0x8a, 0xfc, 0xfb, 0xb0, 0xdd, 0x0e, 0xbe, 0xe1, 0x5e, 0xda, 0x77, 0x97, 0xb3, 0xd0, 0x9d,
	0x20, 0x0d, 0x25, 0xcb, 0x63, 0x95, 0x29, 0x41, 0xf3, 0x67, 0x05, 0x88, 0x13, 0xbb, 0x41, 0x72,
	0x1c, 0xc6, 0xf3, 0xe2, 0x08, 0xd6, 0x29, 0xfc, 0xbe, 0xcc, 0x9f, 0xb4, 0x30, 0xc5, 0xe7, 0x3e,
	0x47, 0xa1, 0x73, 0x21, 0x77, 0x37, 0x8e, 0x10, 0x93, 0xee, 0x98, 0xf0, 0x55, 0x5f, 0x92, 0xc9,
	0x5f, 0xf6, 0x17, 0xeb, 0x02, 0x5d, 0xb8, 0x02, 0xcb, 0x41, 0x9e, 0x56, 0x5e, 0x95, 0xce, 0x76,
	0x5f, 0x57, 0xe5, 0x5f, 0x98, 0xfb, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x19, 0xde, 0xfe,
	0xce, 0x0c, 0x00, 0x00,
}
