// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package session

import (
	fmt "fmt"
	fnexecution_v1 "github.com/apache/beam/sdks/go/pkg/beam/model/fnexecution_v1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Kind int32

const (
	Kind_INVALID              Kind = 0
	Kind_INSTRUCTION_REQUEST  Kind = 1
	Kind_INSTRUCTION_RESPONSE Kind = 2
	Kind_DATA_RECEIVED        Kind = 3
	Kind_DATA_SENT            Kind = 4
	Kind_LOG_ENTRIES          Kind = 5
	Kind_HEADER               Kind = 6
	Kind_FOOTER               Kind = 7
)

var Kind_name = map[int32]string{
	0: "INVALID",
	1: "INSTRUCTION_REQUEST",
	2: "INSTRUCTION_RESPONSE",
	3: "DATA_RECEIVED",
	4: "DATA_SENT",
	5: "LOG_ENTRIES",
	6: "HEADER",
	7: "FOOTER",
}

var Kind_value = map[string]int32{
	"INVALID":              0,
	"INSTRUCTION_REQUEST":  1,
	"INSTRUCTION_RESPONSE": 2,
	"DATA_RECEIVED":        3,
	"DATA_SENT":            4,
	"LOG_ENTRIES":          5,
	"HEADER":               6,
	"FOOTER":               7,
}

func (x Kind) String() string {
	return proto.EnumName(Kind_name, int32(x))
}

func (Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

type Header struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SdkVersion           string   `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	MaxMsgLen            int64    `protobuf:"varint,3,opt,name=max_msg_len,json=maxMsgLen,proto3" json:"max_msg_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Header) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *Header) GetMaxMsgLen() int64 {
	if m != nil {
		return m.MaxMsgLen
	}
	return 0
}

type Footer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Footer) Reset()         { *m = Footer{} }
func (m *Footer) String() string { return proto.CompactTextString(m) }
func (*Footer) ProtoMessage()    {}
func (*Footer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{1}
}

func (m *Footer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Footer.Unmarshal(m, b)
}
func (m *Footer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Footer.Marshal(b, m, deterministic)
}
func (m *Footer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Footer.Merge(m, src)
}
func (m *Footer) XXX_Size() int {
	return xxx_messageInfo_Footer.Size(m)
}
func (m *Footer) XXX_DiscardUnknown() {
	xxx_messageInfo_Footer.DiscardUnknown(m)
}

var xxx_messageInfo_Footer proto.InternalMessageInfo

type EntryHeader struct {
	Len                  int64    `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	Kind                 Kind     `protobuf:"varint,2,opt,name=kind,proto3,enum=org.apache.beam.core.harness.Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryHeader) Reset()         { *m = EntryHeader{} }
func (m *EntryHeader) String() string { return proto.CompactTextString(m) }
func (*EntryHeader) ProtoMessage()    {}
func (*EntryHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{2}
}

func (m *EntryHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryHeader.Unmarshal(m, b)
}
func (m *EntryHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryHeader.Marshal(b, m, deterministic)
}
func (m *EntryHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryHeader.Merge(m, src)
}
func (m *EntryHeader) XXX_Size() int {
	return xxx_messageInfo_EntryHeader.Size(m)
}
func (m *EntryHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EntryHeader proto.InternalMessageInfo

func (m *EntryHeader) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *EntryHeader) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_INVALID
}

type Entry struct {
	Kind Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=org.apache.beam.core.harness.Kind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*Entry_InstReq
	//	*Entry_InstResp
	//	*Entry_Elems
	//	*Entry_LogEntries
	//	*Entry_Header
	//	*Entry_Footer
	Msg                  isEntry_Msg `protobuf_oneof:"msg"`
	Timestamp            int64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{3}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_INVALID
}

type isEntry_Msg interface {
	isEntry_Msg()
}

type Entry_InstReq struct {
	InstReq *fnexecution_v1.InstructionRequest `protobuf:"bytes,1000,opt,name=inst_req,json=instReq,proto3,oneof"`
}

type Entry_InstResp struct {
	InstResp *fnexecution_v1.InstructionResponse `protobuf:"bytes,1001,opt,name=inst_resp,json=instResp,proto3,oneof"`
}

type Entry_Elems struct {
	Elems *fnexecution_v1.Elements `protobuf:"bytes,1002,opt,name=elems,proto3,oneof"`
}

type Entry_LogEntries struct {
	LogEntries *fnexecution_v1.LogEntry_List `protobuf:"bytes,1003,opt,name=log_entries,json=logEntries,proto3,oneof"`
}

type Entry_Header struct {
	Header *Header `protobuf:"bytes,1004,opt,name=header,proto3,oneof"`
}

type Entry_Footer struct {
	Footer *Footer `protobuf:"bytes,1005,opt,name=footer,proto3,oneof"`
}

func (*Entry_InstReq) isEntry_Msg() {}

func (*Entry_InstResp) isEntry_Msg() {}

func (*Entry_Elems) isEntry_Msg() {}

func (*Entry_LogEntries) isEntry_Msg() {}

func (*Entry_Header) isEntry_Msg() {}

func (*Entry_Footer) isEntry_Msg() {}

func (m *Entry) GetMsg() isEntry_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Entry) GetInstReq() *fnexecution_v1.InstructionRequest {
	if x, ok := m.GetMsg().(*Entry_InstReq); ok {
		return x.InstReq
	}
	return nil
}

func (m *Entry) GetInstResp() *fnexecution_v1.InstructionResponse {
	if x, ok := m.GetMsg().(*Entry_InstResp); ok {
		return x.InstResp
	}
	return nil
}

func (m *Entry) GetElems() *fnexecution_v1.Elements {
	if x, ok := m.GetMsg().(*Entry_Elems); ok {
		return x.Elems
	}
	return nil
}

func (m *Entry) GetLogEntries() *fnexecution_v1.LogEntry_List {
	if x, ok := m.GetMsg().(*Entry_LogEntries); ok {
		return x.LogEntries
	}
	return nil
}

func (m *Entry) GetHeader() *Header {
	if x, ok := m.GetMsg().(*Entry_Header); ok {
		return x.Header
	}
	return nil
}

func (m *Entry) GetFooter() *Footer {
	if x, ok := m.GetMsg().(*Entry_Footer); ok {
		return x.Footer
	}
	return nil
}

func (m *Entry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Entry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Entry_InstReq)(nil),
		(*Entry_InstResp)(nil),
		(*Entry_Elems)(nil),
		(*Entry_LogEntries)(nil),
		(*Entry_Header)(nil),
		(*Entry_Footer)(nil),
	}
}

func init() {
	proto.RegisterEnum("org.apache.beam.core.harness.Kind", Kind_name, Kind_value)
	proto.RegisterType((*Header)(nil), "org.apache.beam.core.harness.Header")
	proto.RegisterType((*Footer)(nil), "org.apache.beam.core.harness.Footer")
	proto.RegisterType((*EntryHeader)(nil), "org.apache.beam.core.harness.EntryHeader")
	proto.RegisterType((*Entry)(nil), "org.apache.beam.core.harness.Entry")
}

func init() {
	proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14)
}

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0xf5, 0x4f, 0x9a, 0x13, 0x15, 0x32, 0x83, 0x44, 0x84, 0x26, 0x40, 0x15, 0x17,
	0x88, 0x8b, 0x20, 0x06, 0x42, 0x82, 0x1b, 0xd4, 0xad, 0x19, 0x8d, 0x28, 0x2d, 0x24, 0x59, 0x87,
	0x76, 0x13, 0x65, 0xad, 0xd7, 0x46, 0x6b, 0xe2, 0xcc, 0x4e, 0xa7, 0xf1, 0x18, 0x3c, 0x11, 0xaf,
	0xc3, 0xdf, 0x77, 0xe0, 0xd8, 0xee, 0x26, 0x21, 0xa4, 0xa9, 0x70, 0xe7, 0xf3, 0xf9, 0x7c, 0x3f,
	0xcb, 0xf6, 0x77, 0xa0, 0x2d, 0xa8, 0x10, 0x19, 0x2b, 0xbc, 0x92, 0xb3, 0x8a, 0x91, 0x6d, 0xc6,
	0x67, 0x5e, 0x5a, 0xa6, 0x93, 0x39, 0xf5, 0x8e, 0x69, 0x9a, 0x7b, 0x13, 0xc6, 0xa9, 0x37, 0x4f,
	0x79, 0x81, 0x6d, 0x77, 0xb7, 0xa4, 0x94, 0x9c, 0x14, 0x49, 0x5a, 0x66, 0xda, 0xd0, 0x99, 0x40,
	0xb3, 0x4f, 0xd3, 0x29, 0xe5, 0xc4, 0x05, 0xf3, 0x9c, 0x72, 0xc9, 0x72, 0x8d, 0x07, 0xc6, 0x23,
	0x2b, 0xbc, 0x2c, 0xc9, 0x7d, 0xb0, 0xc5, 0xf4, 0x34, 0xb9, 0xdc, 0xdd, 0x54, 0xbb, 0x80, 0xd2,
	0x78, 0xd5, 0x70, 0x0f, 0xec, 0x3c, 0xbd, 0x48, 0x72, 0x31, 0x4b, 0x16, 0xb4, 0x70, 0x6b, 0xd8,
	0x50, 0x0b, 0x2d, 0x94, 0xde, 0x89, 0xd9, 0x80, 0x16, 0x9d, 0x16, 0x34, 0xf7, 0x19, 0xab, 0x28,
	0xef, 0x1c, 0x82, 0xed, 0x17, 0x15, 0xff, 0xb4, 0x3a, 0xd3, 0x81, 0x9a, 0x34, 0x18, 0xca, 0x20,
	0x97, 0xe4, 0x05, 0xd4, 0x4f, 0xb3, 0x62, 0xaa, 0x0e, 0xb9, 0xb1, 0xd3, 0xf1, 0xae, 0xbb, 0x8f,
	0xf7, 0x16, 0x3b, 0x43, 0xd5, 0xdf, 0xf9, 0x52, 0x87, 0x86, 0x22, 0x5f, 0x11, 0x8c, 0x7f, 0x23,
	0x90, 0x43, 0x68, 0x65, 0x85, 0xa8, 0x12, 0x4e, 0xcf, 0xdc, 0xaf, 0x26, 0x9a, 0xed, 0x9d, 0x97,
	0x7f, 0x99, 0x73, 0x36, 0xa5, 0x0b, 0x0f, 0x5f, 0x90, 0x5e, 0xd0, 0xc9, 0xb2, 0x92, 0x0f, 0x7f,
	0xfe, 0xd4, 0x0b, 0xd0, 0xc7, 0x97, 0x13, 0x59, 0x86, 0xf4, 0x6c, 0x49, 0x45, 0xd5, 0xdf, 0x08,
	0x4d, 0x49, 0xc3, 0x92, 0x1c, 0x81, 0xb5, 0x02, 0x8b, 0xd2, 0xfd, 0xa6, 0xc9, 0xaf, 0xfe, 0x87,
	0x2c, 0x4a, 0x56, 0x08, 0x8a, 0xe8, 0x96, 0x46, 0x8b, 0x92, 0xf4, 0xa1, 0x41, 0x17, 0x34, 0x17,
	0xee, 0x77, 0xcd, 0x7d, 0xb2, 0x26, 0xd7, 0x47, 0x13, 0x2d, 0x2a, 0x81, 0x30, 0x0d, 0x20, 0x1f,
	0xc1, 0x5e, 0xb0, 0x59, 0x82, 0x22, 0xcf, 0xa8, 0x70, 0x7f, 0x68, 0xde, 0xf3, 0x35, 0x79, 0x03,
	0x36, 0x53, 0xaf, 0xef, 0x0d, 0x32, 0x75, 0x79, 0x58, 0x68, 0x01, 0x51, 0xe4, 0x35, 0x34, 0xe7,
	0xea, 0xbb, 0xdd, 0x9f, 0x1a, 0xfa, 0xf0, 0xfa, 0x3f, 0xd1, 0xd9, 0x40, 0xc8, 0xca, 0x26, 0x01,
	0x27, 0x2a, 0x3e, 0xee, 0xaf, 0xb5, 0x00, 0x3a, 0x6b, 0x12, 0xa0, 0x6d, 0x64, 0x1b, 0xac, 0x2a,
	0xcb, 0xf1, 0x5b, 0xd2, 0xbc, 0x54, 0xc9, 0xc2, 0x74, 0x5e, 0x09, 0xbb, 0x0d, 0xa8, 0x61, 0x72,
	0x1f, 0x7f, 0x36, 0xa0, 0x2e, 0xe3, 0x40, 0x6c, 0x30, 0x83, 0xe1, 0xb8, 0x3b, 0x08, 0x7a, 0xce,
	0x06, 0xb9, 0x03, 0xb7, 0x82, 0x61, 0x14, 0x87, 0x07, 0x7b, 0x71, 0x30, 0x1a, 0x26, 0xa1, 0xff,
	0xe1, 0xc0, 0x8f, 0x62, 0xc7, 0xc0, 0x71, 0xb9, 0xfd, 0xe7, 0x46, 0xf4, 0x7e, 0x34, 0x8c, 0x7c,
	0x67, 0x93, 0x6c, 0x41, 0xbb, 0xd7, 0x8d, 0xbb, 0x28, 0xed, 0xf9, 0xc1, 0xd8, 0xef, 0x39, 0x35,
	0xd2, 0x06, 0x4b, 0x49, 0x91, 0x3f, 0x8c, 0x9d, 0x3a, 0xb9, 0x09, 0xf6, 0x60, 0xf4, 0x26, 0xc1,
	0x22, 0x0c, 0xfc, 0xc8, 0x69, 0x10, 0xc0, 0x29, 0xf4, 0xbb, 0x3d, 0x3f, 0x74, 0x9a, 0x72, 0xbd,
	0x3f, 0x1a, 0xc5, 0xb8, 0x36, 0x77, 0xad, 0x23, 0x73, 0x35, 0xdf, 0xc7, 0x4d, 0x35, 0xaf, 0xcf,
	0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x55, 0xbd, 0xb0, 0xf7, 0xf1, 0x03, 0x00, 0x00,
}
